#!/bin/bash
# Starts container from image

CID_FILE=/tmp/docker-flow.pid
rm -rf $CID_FILE
docker run --rm -ti --privileged -p 8080:8080 --cidfile $CID_FILE --name flow hybs/docker_jenkins:latest bash
