#!/bin/bash
# Starts container from image

_NAME_="flow"
_CID_FILE_="/tmp/docker-${_NAME_}.pid"
CID_FILE="--cidfile ${_CID_FILE_}"
PORTS="-p 8080:8080"
VOLUMES="-v /var/lib/jenkins/${_NAME_}:/var/lib/jenkins"
NAME="--name ${_NAME_}"
PRIVILEGED="" # --privileged
IMAGE="hybs/jenkins:${_NAME_}"

rm -rf $_CID_FILE_
ARG=${1:---rm}
shift

echo docker run "$ARG" -ti $PRIVILEGED $PORTS $CID_FILE $VOLUMES $NAME "$@" $IMAGE bash
docker run      "$ARG" -ti $PRIVILEGED $PORTS $CID_FILE $VOLUMES $NAME "$@" $IMAGE bash