#!/bin/bash
# Starts container from image

CID_FILE=/tmp/docker-lib.pid
rm -rf $CID_FILE

ARG=${1:---rm}
shift
echo docker run "$ARG" -ti --privileged -p 8081:8081 --cidfile $CID_FILE --name libs "$@" hybs/jenkins:libs bash
docker run "$ARG" -ti --privileged -p 8081:8081 --cidfile $CID_FILE --name libs "$@" hybs/jenkins:libs bash
