#!/bin/bash
# Starts container from image

CID_FILE=/tmp/docker-flow.pid
rm -rf $CID_FILE

ARG=${1:---rm}
shift
echo docker run "$ARG" -ti --privileged -p 8080:8080 --cidfile $CID_FILE --name flow "$@" hybs/jenkins:flow bash
docker run "$ARG" -ti --privileged -p 8080:8080 --cidfile $CID_FILE --name flow "$@" hybs/jenkins:flow bash
